# 公共配置文件
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api

spring:
  application:
    name: oj-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj_db
    username: root
    password: wm028110
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: wm028110
#   Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  elasticsearch:
    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
  # SpringBootAdmin
  boot:
    admin:
      ui:
        title: 服务状态监控
      ## admin 客户端连接服务端
      client:
        # 为了显示客户端的ip否则是以主机名显示的，这样需要添加hosts影射。
        instance:
          prefer-ip: true
        url: http://localhost:${server.port}/${server.servlet.context-path}/
        #username: admin
        #password: admin@12345
  # naocs
  cloud:
    nacos:
      discovery:
        #必须配置ip地址
        server-addr: localhost:8848
        # 将自己的服务注册到注册中心
        register-enabled: true
        namespace: 08e42c2f-dfb8-44b9-9b3b-a3043740a077
        username: nacos
        password: nacos
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
      config:
        server-addr: localhost:8848
        enabled: true
        file-extension: yaml
        namespace: 08e42c2f-dfb8-44b9-9b3b-a3043740a077
        username: nacos
        password: nacos
        import-check:
          enabled: false

# 开启全部
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx

# 接口文档配置
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
